"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Optional: load environment variables from a .env file next to manage.py (webapp/.env) if
# present, so the deployer can keep secrets/config in one un-committed file instead of exporting
# many variables. Values already set in the real environment always win (setdefault).
def _load_dotenv(path: Path) -> None:
    try:
        with open(path, encoding="utf-8") as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, val = line.split("=", 1)
                os.environ.setdefault(key.strip(), val.strip().strip('"').strip("'"))
    except FileNotFoundError:
        pass


_load_dotenv(BASE_DIR / ".env")

# The report engine lives in the sibling send_report/ package (one level above webapp/).
# Add it to the path so `import generate_report` works from the reports app's service layer.
SEND_REPORT_DIR = (BASE_DIR.parent / "send_report").resolve()
if str(SEND_REPORT_DIR) not in sys.path:
    sys.path.insert(0, str(SEND_REPORT_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment in production; the insecure default is only for local dev.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-e1ij0vxafgh$*or#6c4umcg^7(2-goy0_$ks1ms+^mw#mvr0&p",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# Domains/IPs this app will answer to. Add the web domain you want here (comma-separated),
# e.g. DJANGO_ALLOWED_HOSTS="admin-report.rbz.co.zw,localhost,127.0.0.1".
# NOTE: this only tells Django to accept that Host header — DNS for the name must still
# resolve to this server's IP, and the server must be bound to the network (0.0.0.0).
ALLOWED_HOSTS = [
    h.strip() for h in
    os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,admin-report.rbz.co.zw").split(",")
    if h.strip()
]

# CSRF needs the exact scheme+host for cross-origin POSTs (login, generate) over a real
# domain. Auto-trust http/https for each non-local host, or override via env.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
if not CSRF_TRUSTED_ORIGINS:
    for _h in ALLOWED_HOSTS:
        if _h not in ("localhost", "127.0.0.1", "0.0.0.0", "*"):
            CSRF_TRUSTED_ORIGINS += [f"https://{_h}", f"http://{_h}"]

# Show our own "your session expired" page instead of Django's bare CSRF 403, which tells an
# admin nothing and leaves them stranded mid-report.
CSRF_FAILURE_VIEW = "reports.views.csrf_failure"

# IIS+ARR now terminates TLS in front of waitress (deployment.txt §9) and forwards
# X-Forwarded-Proto: https, so Django can tell a proxied request was originally HTTPS.
# SAFE ONLY as long as waitress itself isn't reachable by untrusted clients directly —
# see deployment.txt for the loopback-binding note.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# How long a captured snapshot stays valid between loading the form and generating the
# report (seconds). Keeps the answers married to the exact numbers the admin reviewed.
SNAPSHOT_TTL = int(os.environ.get("REPORT_SNAPSHOT_TTL", "600"))   # 10 minutes


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reports.middleware.RoleRequiredMiddleware',
    'reports.middleware.RoleScopeMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'reports.context.role_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# PostgreSQL is the production store for all data (users, profiles, roles, submissions, …).
# Configure it with POSTGRES_* env vars; without them we fall back to SQLite for local dev.
# Migrations are database-agnostic, so the same schema applies to both.
if os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Zimbabwe (CAT, UTC+2). USE_TZ stays on, so timestamps are stored in UTC but displayed
# in this local zone — history now reads e.g. 23:20, matching when reports were actually run.
TIME_ZONE = 'Africa/Harare'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'      # collectstatic target for production

# No reverse proxy is fronting this deployment yet (IP-only access, no DNS), so
# WhiteNoise serves /static/ directly from the app instead of relying on a proxy.
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Authentication: the whole app is gated (see LoginRequiredMixin / @login_required).
LOGIN_URL = 'login'
# Land on the role picker after signing in. It forwards straight through when the
# user holds one role or none, so only people with a real choice ever see it.
LOGIN_REDIRECT_URL = 'role_select'
LOGOUT_REDIRECT_URL = 'login'

# Session inactivity timeout: log an admin out after 15 minutes of no activity.
# SESSION_SAVE_EVERY_REQUEST makes this a SLIDING (idle) timeout — every request
# re-stamps the cookie's expiry, so the 15-minute clock only runs down while the
# admin is idle; once it lapses the session is gone and login_required bounces them
# back to the login page. Override with DJANGO_SESSION_TIMEOUT (seconds) if needed.
SESSION_COOKIE_AGE = int(os.environ.get("DJANGO_SESSION_TIMEOUT", str(15 * 60)))   # 900s = 15 min
SESSION_SAVE_EVERY_REQUEST = True

# Org auth endpoint (JSON username/password) is tried first (no-op until config.ini [auth]
# enabled=true), then the local ModelBackend — so the built-in 'admin' always still works.
AUTHENTICATION_BACKENDS = [
    'reports.directory.HttpAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Snapshots are cached in-process between the form and generation. The default local-memory
# cache is fine for a single-worker deployment; point CACHES at Redis/Memcached if you run
# multiple workers so both requests see the same snapshot.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'report-snapshots',
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
