# Generated by Django 5.1.15 on 2026-07-17 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, help_text='Name signed on the report', max_length=120)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('prom_url', models.CharField(blank=True, max_length=256)),
                ('systems_count', models.PositiveIntegerField(default=0)),
                ('hosts_count', models.PositiveIntegerField(default=0)),
                ('immediate_count', models.PositiveIntegerField(default=0)),
                ('watch_count', models.PositiveIntegerField(default=0)),
                ('summary_comment', models.TextField(blank=True)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('filename', models.CharField(blank=True, max_length=256)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
