# Generated by Django 5.1.15 on 2026-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubmission',
            name='delivery',
            field=models.CharField(choices=[('download', 'Download'), ('email', 'Email')], default='download', max_length=10),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='recipients',
            field=models.CharField(blank=True, help_text='Comma-separated, if emailed', max_length=512),
        ),
    ]
