# Generated by Django 5.1.15 on 2026-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportsubmission_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Display name (optional)', max_length=120)),
                ('default_selected', models.BooleanField(default=False, help_text='Pre-ticked in the send dialog')),
                ('active', models.BooleanField(default=True, help_text='Untick to hide without deleting')),
            ],
            options={
                'verbose_name': 'email recipient',
                'ordering': ['name', 'email'],
            },
        ),
    ]
