# Generated by Django 5.1.15 on 2026-07-17 19:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_seed_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=64)),
                ('job_title', models.CharField(blank=True, max_length=128)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces and + ( ) - . only).', regex='^[0-9+()\\-.\\s]{3,40}$')])),
                ('mobile', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces and + ( ) - . only).', regex='^[0-9+()\\-.\\s]{3,40}$')])),
                ('office_location', models.CharField(blank=True, max_length=128)),
                ('distinguished_name', models.CharField(blank=True, max_length=512, verbose_name='distinguished name (LDAP)')),
                ('default_report_theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('page_theme', models.CharField(choices=[('system', 'Follow system'), ('dark', 'Dark'), ('light', 'Light')], default='system', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ldap', 'LDAP')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['employee_id'], name='reports_use_employe_158be7_idx'), models.Index(fields=['department'], name='reports_use_departm_f3d5ea_idx')],
            },
        ),
    ]
