# Generated by Django 5.1.15 on 2026-07-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_backfill_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prometheus_url', models.URLField(blank=True, help_text='Prometheus base URL the dashboard fetches from (blank = use config.ini)', max_length=256)),
                ('grafana_url', models.URLField(blank=True, help_text='Live Grafana dashboard URL (blank = use config.ini)', max_length=1024)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system configuration',
                'verbose_name_plural': 'system configuration',
            },
        ),
    ]
