# Generated by Django 5.1.15 on 2026-07-17 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_systemconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='grafana_url',
            field=models.CharField(blank=True, help_text='Live Grafana dashboard URL (blank = use config.ini)', max_length=1024, validators=[django.core.validators.RegexValidator(message='Enter a URL starting with http:// or https://', regex='^https?://\\S+$')]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='prometheus_url',
            field=models.CharField(blank=True, help_text='Prometheus base URL the dashboard fetches from (blank = use config.ini)', max_length=256, validators=[django.core.validators.RegexValidator(message='Enter a URL starting with http:// or https://', regex='^https?://\\S+$')]),
        ),
    ]
