# Generated by Django 5.1.15 on 2026-07-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_systemconfig_grafana_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubmission',
            name='report_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, help_text='When this user last opened notifications', null=True),
        ),
    ]
