# Generated by Django 5.1.15 on 2026-08-17 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_seed_security_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafanaConfigRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text='What changed and why (optional)', max_length=200)),
                ('protocol', models.CharField(choices=[('https', 'https'), ('http', 'http')], default='https', max_length=8)),
                ('cert_file', models.CharField(blank=True, max_length=512)),
                ('cert_key', models.CharField(blank=True, max_length=512)),
                ('root_url', models.CharField(blank=True, max_length=512, validators=[django.core.validators.RegexValidator(message='Enter a URL starting with http:// or https://', regex='^https?://\\S+$')])),
                ('allow_embedding', models.BooleanField(default=True)),
                ('smtp_enabled', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(blank=True, max_length=256)),
                ('smtp_user', models.CharField(blank=True, max_length=256)),
                ('smtp_password_encrypted', models.TextField(blank=True, help_text='Fernet ciphertext — see reports/crypto.py. Never plaintext.')),
                ('smtp_skip_verify', models.BooleanField(default=False)),
                ('smtp_from_address', models.CharField(blank=True, max_length=256)),
                ('smtp_from_name', models.CharField(blank=True, max_length=128)),
                ('smtp_ehlo_identity', models.CharField(blank=True, max_length=128)),
                ('smtp_starttls_policy', models.CharField(choices=[('Always', 'Always'), ('OpportunisticStartTLS', 'OpportunisticStartTLS'), ('MandatoryStartTLS', 'MandatoryStartTLS'), ('NoStartTLS', 'NoStartTLS')], default='Always', max_length=32)),
                ('execute_alerts', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grafana config revision',
                'ordering': ['-created_at'],
            },
        ),
    ]
