# Generated by Django 5.1.15 on 2026-08-17 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_prometheusconfigrevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='allow_embedding',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='cert_file',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='cert_key',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='execute_alerts',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='root_url',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='smtp_ehlo_identity',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='smtp_enabled',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='smtp_from_address',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='smtp_from_name',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='smtp_skip_verify',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='smtp_starttls_policy',
        ),
        migrations.RemoveField(
            model_name='grafanaconfigrevision',
            name='smtp_user',
        ),
        migrations.AddField(
            model_name='grafanaconfigrevision',
            name='content',
            field=models.TextField(default='', help_text='The entire custom.ini text, MASKED (see class docstring).'),
        ),
        migrations.CreateModel(
            name='PrometheusRuleFileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text='What changed and why (optional)', max_length=200)),
                ('filename', models.CharField(choices=[('alerts.yml', 'alerts.yml'), ('t24_services.yml', 't24_services.yml'), ('folder_exporter_rules.yml', 'folder_exporter_rules.yml')], max_length=64)),
                ('content', models.TextField(help_text="The entire rule file's text.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prometheus rule file revision',
                'ordering': ['-created_at'],
            },
        ),
    ]
