# Generated by Django 5.1.15 on 2026-08-17 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_rolescope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnmpConfigRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text='What changed and why (optional)', max_length=200)),
                ('profiles', models.JSONField(default=dict, help_text='{profile: {field: value, ...}}, secrets MASKED (see class docstring).')),
                ('secrets_encrypted', models.JSONField(default=dict, help_text='{profile: {field: ciphertext, ...}} — Fernet, never plaintext.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SNMP config revision',
                'ordering': ['-created_at'],
            },
        ),
    ]
