# Generated by Django 5.1.15 on 2026-08-17 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_backuppolicyrevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What this checks, e.g. 'BSA SQL backup'. Becomes the filename stem.", max_length=120)),
                ('script_type', models.CharField(help_text='Key from reports.scripts.SCRIPT_TYPES', max_length=32)),
                ('system', models.CharField(blank=True, help_text='The system in prometheus.yml this belongs to — for the generated header, so a file on a host says which estate it serves.', max_length=120)),
                ('host', models.CharField(blank=True, help_text="Where it runs. Recorded for the operator; the script itself doesn't use it.", max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Non-secret field values. NEVER put a credential here — see secrets_encrypted.')),
                ('secrets_encrypted', models.TextField(blank=True, help_text='Fernet ciphertext — see reports/crypto.py. Never plaintext.')),
                ('notes', models.TextField(blank=True, help_text='Anything the next person needs to know.')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_generated_files', models.JSONField(blank=True, default=list, help_text='Paths written by the last generate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'generated script',
                'ordering': ['script_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('script_type', 'name'), name='unique_script_name_per_type')],
            },
        ),
    ]
