# Generated by Django 5.1.15 on 2026-09-03 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_generatedscript'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('systems', models.JSONField(blank=True, default=list, help_text='System names from prometheus.yml this group covers. Empty = covers nothing yet (unlike Role scopes, empty here is not ‘all systems’).')),
                ('emails', models.JSONField(blank=True, default=list, help_text='Plain e-mail addresses for stakeholders with no account.')),
                ('min_severity', models.CharField(choices=[('red', 'Red only'), ('amber', 'Red + Amber')], default='red', max_length=10)),
                ('renotify_mode', models.CharField(choices=[('once', 'Once per finding, then silent until resolved'), ('daily', 'Once, then a daily reminder while still open')], default='once', max_length=10)),
                ('active', models.BooleanField(default=True, help_text='Untick to pause without deleting.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, help_text='App users notified via their account e-mail.', related_name='alert_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alert group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=120)),
                ('flag_key', models.CharField(max_length=255)),
                ('band', models.CharField(max_length=10)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reports.alertgroup')),
            ],
            options={
                'verbose_name': 'alert finding state',
                'ordering': ['-last_seen_at'],
                'unique_together': {('group', 'system', 'flag_key')},
            },
        ),
    ]
