# Generated by Django 5.1.15 on 2026-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_alertgroup_alertfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Flag categories (disk/ram/cpu/...) this group alerts on. UNLIKE `systems` above, empty here means ALL categories, not none -- this field was added after groups already existed in the wild, and an empty-means-nothing default would have silently gone quiet for every one of them the moment the field appeared. Narrow it explicitly if you only want e.g. backup alerts for this group.'),
        ),
    ]
