# Generated by Django 5.1.15 on 2026-09-03 09:09

from django.db import migrations, models


def _flatten_to_per_system(apps, schema_editor):
    """categories used to be a flat list (global, all-systems). Convert every existing row to
    the new {system: [category, ...]} shape: an old empty list ([] = "all") becomes an empty
    dict ({} = "all", same meaning, just nested one level); a NARROWED old list is applied
    identically to every system already on that group, preserving exactly what it used to mean
    (that flat list applied globally) rather than silently discarding the narrowing."""
    AlertGroup = apps.get_model("reports", "AlertGroup")
    for g in AlertGroup.objects.all():
        old = g.categories
        if isinstance(old, list) and old:
            g.categories = {s: list(old) for s in (g.systems or [])}
            g.save(update_fields=["categories"])
        elif isinstance(old, list):
            g.categories = {}
            g.save(update_fields=["categories"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_alertgroup_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertgroup',
            name='categories',
            field=models.JSONField(blank=True, default=dict, help_text='{system name: [category, ...]} -- per-system, not global, since not every system tracks the same things (e.g. only some have named service checks). A system ABSENT from this dict, or present with an empty list, means ALL categories for THAT system -- unlike `systems` above, missing/empty here means everything, not nothing, because this field was added after groups already existed in the wild and an empty-means-nothing default would have silently gone quiet for every one of them the moment it appeared.'),
        ),
        migrations.RunPython(_flatten_to_per_system, migrations.RunPython.noop),
    ]
