# Generated by Django 5.1.15 on 2026-09-03 09:31

from django.db import migrations, models


def _convert_renotify_mode(apps, schema_editor):
    """renotify_mode used to be a two-way choice ("once" / "daily", a fixed 24h cadence) --
    convert every existing row to the new, genuinely configurable minutes field before the old
    column is dropped below: "once" -> None (fire once, then silent -- unchanged meaning),
    "daily" -> 1440 (the exact number of minutes "daily" always meant, so a group already set
    to daily reminders keeps behaving identically, just expressed as a number now)."""
    AlertGroup = apps.get_model("reports", "AlertGroup")
    for g in AlertGroup.objects.all():
        g.renotify_interval_minutes = 1440 if g.renotify_mode == "daily" else None
        g.save(update_fields=["renotify_interval_minutes"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_alter_alertgroup_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='renotify_interval_minutes',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Re-notify at least this often while a finding stays open. Blank or 0 = fire once, then stay silent until resolved.', null=True),
        ),
        migrations.RunPython(_convert_renotify_mode, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='alertgroup',
            name='renotify_mode',
        ),
    ]
