# Generated by Django 5.1.15 on 2026-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_remove_alertgroup_renotify_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertgroup',
            name='renotify_interval_minutes',
        ),
        migrations.AddField(
            model_name='alertfinding',
            name='first_notified_at',
            field=models.DateTimeField(blank=True, help_text="When this finding's notification FIRST succeeded — the schedule's own anchor point. Reset alongside reminder_count on reopen/escalation.", null=True),
        ),
        migrations.AddField(
            model_name='alertfinding',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many of the 3 scheduled reminders have gone out so far.'),
        ),
    ]
