# Generated by Django 5.1.15 on 2026-09-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_backfill_first_notified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertfinding',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0, help_text="How many scheduled reminders have gone out so far (cap = AlertScheduleConfig's current reminder count)."),
        ),
        migrations.CreateModel(
            name='AlertScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_minutes', models.JSONField(blank=True, default=list, help_text='Ascending minutes-after-first-notification, one per reminder. Empty = use the shipped default (10, 40, 60).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alert reminder schedule',
                'verbose_name_plural': 'alert reminder schedule',
            },
        ),
    ]
