# Generated by Django 5.1.15 on 2026-09-04 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_alter_alertfinding_reminder_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertscheduleconfig',
            options={'verbose_name': 'notification reminder schedule', 'verbose_name_plural': 'notification reminder schedule'},
        ),
        migrations.CreateModel(
            name='DrainageThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amber_seconds', models.PositiveIntegerField(blank=True, help_text="Seconds before a queue folder's oldest file counts as drifting. Blank = use the default (5 minutes).", null=True)),
                ('red_seconds', models.PositiveIntegerField(blank=True, help_text="Seconds before a queue folder's oldest file counts as a fault. Blank = use the default (10 minutes).", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'drainage threshold configuration',
                'verbose_name_plural': 'drainage threshold configuration',
            },
        ),
    ]
