# Generated by Django 5.1.15 on 2026-09-04 08:35

from django.db import migrations, models


def _migrate_schedule_and_severity(apps, schema_editor):
    """One-time data migration (2026-09-04): the reminder schedule moves from a single
    app-wide AlertScheduleConfig singleton to a per-AlertGroup field ("notification reminder
    schedule should be group specific") -- copy whatever custom schedule was saved there onto
    EVERY existing group, so no group's behaviour changes the moment this ships (a group with
    nothing copied just keeps falling back to the same shipped default it already used).

    Also folds the removed "amber"/"Warning and above" min_severity choice into "red" ("there
    are no expected alerts for warning severity...only imminent and critical thresholds") --
    any group that had opted into Warning now reads Critical & Imminent only, the only choice
    left."""
    AlertGroup = apps.get_model("reports", "AlertGroup")
    AlertScheduleConfig = apps.get_model("reports", "AlertScheduleConfig")

    sc = AlertScheduleConfig.objects.filter(pk=1).first()
    if sc and sc.reminder_minutes:
        AlertGroup.objects.update(reminder_minutes=sc.reminder_minutes)

    AlertGroup.objects.filter(min_severity="amber").update(min_severity="red")


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_alter_alertscheduleconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='reminder_minutes',
            field=models.JSONField(blank=True, default=list, help_text='Ascending minutes-after-first-notification, one per reminder, for THIS group. Empty = use the shipped default (10, 40, 60).'),
        ),
        migrations.RunPython(_migrate_schedule_and_severity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='alertfinding',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0, help_text="How many scheduled reminders have gone out so far (cap = this finding's own group's current reminder count)."),
        ),
        migrations.AlterField(
            model_name='alertgroup',
            name='min_severity',
            field=models.CharField(choices=[('red', 'Critical & Imminent only')], default='red', max_length=10),
        ),
        migrations.DeleteModel(
            name='AlertScheduleConfig',
        ),
    ]
