# Generated by Django 5.1.15 on 2026-09-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_alertgroup_reminder_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainagethresholdconfig',
            name='backup_red_seconds',
            field=models.PositiveIntegerField(blank=True, help_text="Seconds before a BACKUP folder's oldest file counts as a fault, overriding the automatic per-system backup-cadence calculation. Blank = keep the automatic calculation.", null=True),
        ),
    ]
