# Generated by Django 5.1.15 on 2026-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_drainagethresholdconfig_backup_red_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drainagethresholdconfig',
            name='backup_red_seconds',
        ),
        migrations.AddField(
            model_name='drainagethresholdconfig',
            name='backup_red_seconds_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='{system name: seconds} -- an explicit override, per system, onto the otherwise-automatic backup-cadence calculation for BACKUP folders. A system absent from this dict keeps its automatic value.'),
        ),
    ]
