# Generated by Django 5.1.15 on 2026-09-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_remove_drainagethresholdconfig_backup_red_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='imminent_reminder_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='How often (minutes) an unresolved IMMINENT finding (component unreachable) re-reminds, forever, until resolved. Blank = 10.', null=True),
        ),
    ]
