# Generated by Django 5.1.15 on 2026-09-04 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_alertgroup_imminent_reminder_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('systems', models.JSONField(blank=True, default=list, help_text='System names from prometheus.yml this group covers. Empty = covers nothing yet.')),
                ('emails', models.JSONField(blank=True, default=list, help_text='Plain e-mail addresses for stakeholders with no account.')),
                ('active', models.BooleanField(default=True, help_text='Untick to pause without deleting.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, help_text='App users notified via their account e-mail.', related_name='event_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeenBackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=120)),
                ('instance', models.CharField(max_length=120)),
                ('filename', models.CharField(max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'seen backup file',
                'unique_together': {('system', 'instance', 'filename')},
            },
        ),
    ]
