# Generated by Django 5.1.15 on 2026-09-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_eventgroup_seenbackupfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seenbackupfile',
            options={},
        ),
        migrations.CreateModel(
            name='FreshnessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What this checks, e.g. "T24 TSA Services Checker".', max_length=200)),
                ('system', models.CharField(help_text='System name from prometheus.yml this checker belongs to -- a SystemAlertGroup covering this system is notified when it goes stale.', max_length=120)),
                ('instance', models.CharField(help_text='Scrape target serving this file, e.g. "10.0.212.3:9182".', max_length=200)),
                ('file', models.CharField(help_text='The .prom filename windows_exporter\'s textfile collector reports under the `file` label, e.g. "t24_services.prom".', max_length=255)),
                ('max_age_seconds', models.PositiveIntegerField(default=7200, help_text="How old this file's own last write may get before it's considered stale. Set this to comfortably more than the checker's real run interval, or every normal gap between runs will falsely alert.")),
                ('active', models.BooleanField(default=True, help_text='Untick to stop watching without deleting.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'freshness check',
                'ordering': ['system', 'name'],
                'unique_together': {('instance', 'file')},
            },
        ),
        migrations.CreateModel(
            name='SystemAlertGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('systems', models.JSONField(blank=True, default=list, help_text='System names from prometheus.yml this group hears staleness for. Empty = covers nothing yet.')),
                ('emails', models.JSONField(blank=True, default=list, help_text='Plain e-mail addresses for stakeholders with no account.')),
                ('reminder_minutes', models.PositiveIntegerField(default=60, help_text='How often (minutes) an unresolved stale checker re-reminds, forever, until it starts updating again.')),
                ('active', models.BooleanField(default=True, help_text='Untick to pause without deleting.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, help_text='App users notified via their account e-mail.', related_name='system_alert_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system alert group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlertFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField()),
                ('first_notified_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('freshness_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reports.freshnesscheck')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reports.systemalertgroup')),
            ],
            options={
                'verbose_name': 'system alert finding state',
                'ordering': ['-first_seen_at'],
                'unique_together': {('group', 'freshness_check')},
            },
        ),
    ]
