# Generated by Django 5.1.15 on 2026-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_seed_t24_freshness_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshnesscheck',
            name='scheduler_instance',
            field=models.CharField(blank=True, help_text='Optional: the folder_exporter instance running this checker as a scheduled job, e.g. "10.0.212.3:9847" (NOT the same port as the textfile-collector Instance above). Leave blank if this file isn\'t produced by a folder_exporter job.', max_length=200),
        ),
        migrations.AddField(
            model_name='freshnesscheck',
            name='scheduler_job',
            field=models.CharField(blank=True, help_text='Optional: that job\'s own name (folder_exporter.yml\'s `jobs: - name:`), e.g. "t24_service_checker" -- shown as scheduler_job_last_success_timestamp_seconds\'s `exported_job` label.', max_length=200),
        ),
    ]
