# Generated by Django 5.1.15 on 2026-09-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_seed_t24_scheduler_correlation'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshnesscheck',
            name='kind',
            field=models.CharField(choices=[('textfile_mtime', 'Textfile mtime (windows_exporter, needs a file)'), ('backup_check', 'Backup checker timestamp (any host, no file needed)')], default='textfile_mtime', max_length=20),
        ),
        migrations.AlterField(
            model_name='freshnesscheck',
            name='file',
            field=models.CharField(blank=True, help_text='Required for "Textfile mtime" only: the .prom filename windows_exporter\'s textfile collector reports under the `file` label, e.g. "t24_services.prom". Leave blank for "Backup checker timestamp".', max_length=255),
        ),
        migrations.AlterField(
            model_name='freshnesscheck',
            name='instance',
            field=models.CharField(help_text='Scrape target serving this signal, e.g. "10.0.212.3:9182".', max_length=200),
        ),
    ]
