# Generated by Django 5.1.15 on 2026-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_freshnesscheck_kind_alter_freshnesscheck_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='alert_subtype',
            field=models.CharField(blank=True, choices=[('staleness', 'Staleness Alert')], default='', help_text='Only meaningful when alert_type is System Alert. Blank for Monitoring Alert.', max_length=20),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='alert_type',
            field=models.CharField(choices=[('monitoring', 'Monitoring Alert'), ('system', 'System Alert')], default='monitoring', help_text="Set at creation; not changed afterward (see this model's own docstring).", max_length=20),
        ),
    ]
