# Generated by Django 5.1.15 on 2026-09-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_merge_systemalertgroup_into_alertgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemalertfinding',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_alert_findings', to='reports.alertgroup'),
        ),
        migrations.DeleteModel(
            name='SystemAlertGroup',
        ),
    ]
