# Generated by Django 5.1.15 on 2026-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_alter_systemalertfinding_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list, help_text='0=Monday .. 6=Sunday. Empty while schedule_enabled means every day.'),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='schedule_enabled',
            field=models.BooleanField(default=False, help_text='Restrict this group to a recurring day/time window. Off = always active (subject only to the Active toggle above).'),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='schedule_end',
            field=models.TimeField(blank=True, help_text='Daily window end (local time). Earlier than Start means the window crosses midnight, e.g. 22:00 -> 06:00.', null=True),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='schedule_start',
            field=models.TimeField(blank=True, help_text='Daily window start (local time). Blank with schedule_end also blank = all day (only schedule_days restricts it).', null=True),
        ),
    ]
