# Generated by Django 5.1.15 on 2026-09-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0041_alertgroup_schedule_days_alertgroup_schedule_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='anthropic_api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='copilot_api_key_encrypted',
            field=models.TextField(blank=True, default='', help_text="Reserved slot for the company's own Microsoft 365 Copilot API key -- no working Copilot integration exists yet (see reports/ai_narrative.py), selecting this provider currently always falls back to the offline narrative regardless of whether a key is stored here."),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='narrative_provider',
            field=models.CharField(blank=True, choices=[('', 'Off (statistics only)'), ('anthropic', 'Anthropic (Claude)'), ('copilot', 'Microsoft 365 Copilot — not yet implemented, reserved for your own key')], default='', help_text='Which AI provider the Automated Reports engine calls for the narrative sections. A report always generates even if this is off, unreachable, or misconfigured -- see reports/ai_narrative.py.', max_length=20),
        ),
    ]
