# Generated by Django 5.1.15 on 2026-09-07 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0042_systemconfig_anthropic_api_key_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedReportInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly_trend', 'Weekly Operational Trend Report'), ('monthly_recurring', 'Monthly Recurring Issues Report'), ('quarterly_summary', 'Quarterly Management Summary'), ('system_attention', 'System Attention Report'), ('admin_observations', 'Administrator Observations Digest'), ('anomaly_log', 'Anomaly / Fluke Log')], db_index=True, max_length=32)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('ai_provider', models.CharField(blank=True, default='', max_length=20)),
                ('ai_requested_provider', models.CharField(blank=True, default='', max_length=20)),
                ('ai_error', models.TextField(blank=True, default='')),
                ('content', models.JSONField(blank=True, default=dict)),
                ('distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'automated report instance',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='receives_automated_reports',
            field=models.BooleanField(default=False, help_text="Gets scheduled Automated Reports e-mails once distribution is enabled (a separate list from 'Pre-ticked in the send dialog', which only affects manually generated reports)."),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='automated_reports_distribution_enabled',
            field=models.BooleanField(default=False, help_text='Off = shadow mode: reports generate and store on schedule but are not e-mailed. Review generated reports for accuracy before enabling.'),
        ),
    ]
