# Generated by Django 5.1.15 on 2026-09-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_automatedreportinstance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=120)),
                ('flag_key', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=40)),
                ('band', models.CharField(max_length=10)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'issue occurrence',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['system', 'started_at'], name='reports_iss_system_77e094_idx'), models.Index(fields=['category', 'started_at'], name='reports_iss_categor_3e02a4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('system', 'flag_key'), name='one_open_issue_occurrence_per_system_flag')],
            },
        ),
    ]
