# Generated by Django 5.1.15 on 2026-09-08 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0044_issueoccurrence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('report_types', models.JSONField(blank=True, default=list, help_text='Which automated report types this group receives. Empty = receives nothing yet.')),
                ('emails', models.JSONField(blank=True, default=list, help_text='Plain e-mail addresses for stakeholders with no account.')),
                ('active', models.BooleanField(default=True, help_text='Untick to pause without deleting.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, help_text='App users notified via their account e-mail.', related_name='automated_report_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'automated report group',
                'ordering': ['name'],
            },
        ),
    ]
