# Generated by Django 5.1.15 on 2026-09-10 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0046_migrate_automated_report_recipients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedFindingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=120)),
                ('flag_key', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('fix_needed', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], default='', max_length=8)),
                ('resolved', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], default='', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'automated report finding action',
                'unique_together': {('system', 'flag_key')},
            },
        ),
    ]
