# Generated by Django 5.1.15 on 2026-09-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0048_seed_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolescope',
            name='can_edit_own_alert_groups',
            field=models.BooleanField(default=False, help_text="Members may edit an Alert group they belong to (add stakeholders, not remove; can't delete the group). A general opt-in, not hardcoded to one role — see roles.can_edit_alert_group()."),
        ),
    ]
