# Generated by Django 5.1.15 on 2026-09-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0049_rolescope_can_edit_own_alert_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=255)),
                ('taken_at', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name': 'metric sample',
                'ordering': ['taken_at'],
                'indexes': [models.Index(fields=['metric_key', 'taken_at'], name='reports_met_metric__11bbd6_idx')],
                'constraints': [models.UniqueConstraint(fields=('metric_key', 'taken_at'), name='unique_metric_sample_point')],
            },
        ),
    ]
