# Generated by Django 5.1.15 on 2026-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_metricsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEstateOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40, unique=True)),
                ('captured_at', models.DateTimeField()),
                ('overview', models.JSONField()),
                ('systems', models.JSONField()),
            ],
            options={
                'verbose_name': 'live estate overview',
            },
        ),
    ]
