# Generated by Django 5.1.15 on 2026-09-18 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0051_liveestateoverview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSilence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=120)),
                ('flag_key', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Silencing stops automatically after this date -- a deliberate renewal, not a permanent standing rule, keeps this reviewed periodically.')),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Whose digest this rolls into -- normally the same group that would otherwise be notified for it.', on_delete=django.db.models.deletion.CASCADE, related_name='silences', to='reports.alertgroup')),
            ],
            options={
                'verbose_name': 'alert silence',
                'ordering': ['-created_at'],
            },
        ),
    ]
