# Generated by Django 5.1.15 on 2026-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0052_alertsilence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=120)),
                ('if_index', models.CharField(max_length=20)),
                ('if_name', models.CharField(blank=True, max_length=255)),
                ('first_seen_up_at', models.DateTimeField()),
                ('last_seen_up_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField()),
                ('currently_up', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'monitored interface baseline',
                'unique_together': {('device', 'if_index')},
            },
        ),
    ]
