# Generated by Django 5.1.15 on 2026-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0053_monitoredinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredinterface',
            name='is_scoped',
            field=models.BooleanField(default=False, help_text="Ever CDP-identified as an AP/uplink/neighbour link -- sticky, see this model's own docstring for why it must never be unset once True."),
        ),
    ]
