# Generated by Django 5.1.15 on 2026-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0054_monitoredinterface_is_scoped'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredAccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=120)),
                ('ap_name', models.CharField(max_length=255)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField()),
                ('currently_up', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'monitored access point baseline',
                'unique_together': {('device', 'ap_name')},
            },
        ),
    ]
