# Generated by Django 5.1.15 on 2026-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0056_metricsampleretentionrevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('database', models.CharField(max_length=100)),
                ('destination_path', models.CharField(blank=True, max_length=500)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Database backup run',
                'ordering': ['-started_at'],
            },
        ),
    ]
