# Generated by Django 5.1.15 on 2026-09-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0057_databasebackuprun'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueoccurrence',
            name='domain',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
