# Generated by Django 5.1.15 on 2026-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0059_backfill_issueoccurrence_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsilence',
            name='category',
            field=models.CharField(blank=True, choices=[('disk', 'Disk usage'), ('ram', 'Ram usage'), ('cpu', 'Cpu usage'), ('service', 'Service down'), ('backup', 'Backup missing'), ('unreachable', 'Component unreachable'), ('untracked', 'Backup untracked'), ('folder', 'Size monitoring'), ('backup_uncleared', 'Backup & log drainage'), ('undrained_folders', 'Drainage monitoring')], help_text='What this silences (reports.alerting.Flag.category).', max_length=32),
        ),
        migrations.AlterField(
            model_name='alertsilence',
            name='flag_key',
            field=models.CharField(blank=True, help_text='One specific component (e.g. disk:Database:/u01). Blank = every component under `category` for this system, including ones added later.', max_length=255),
        ),
    ]
