# Generated by Django 5.1.15 on 2026-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0060_alertsilence_category_alter_alertsilence_flag_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsilence',
            name='category',
            field=models.CharField(blank=True, choices=[('disk', 'Disk usage'), ('ram', 'Ram usage'), ('cpu', 'Cpu usage'), ('service', 'Service down'), ('degraded', 'Degraded'), ('backup', 'Backup missing'), ('unreachable', 'Component unreachable'), ('untracked', 'Backup untracked'), ('folder', 'Size monitoring'), ('backup_uncleared', 'Backup & log drainage'), ('undrained_folders', 'Drainage monitoring')], help_text='What this silences (reports.alerting.Flag.category).', max_length=32),
        ),
    ]
