# Generated by Django 5.1.15 on 2026-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0069_alter_alertsilence_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsilence',
            name='category',
            field=models.CharField(blank=True, choices=[('disk', 'Disk usage'), ('very_high_disk', 'Very high disk usage'), ('ram', 'Ram usage'), ('cpu', 'Cpu usage'), ('service', 'Service down'), ('degraded', 'Degraded'), ('degrading', 'Degrading'), ('potentially_degrading', 'Potentially degrading'), ('temperature', 'Temperature'), ('backup', 'Backup missing'), ('unreachable', 'Component unreachable'), ('untracked', 'Backup untracked'), ('untracked_metrics', 'Untracked metrics'), ('folder', 'Size monitoring'), ('backup_uncleared', 'Backup & log drainage'), ('backup_overdue', 'Backup & log drainage overdue'), ('undrained_folders', 'Drainage monitoring')], help_text='What this silences (reports.alerting.Flag.category).', max_length=32),
        ),
    ]
