# Generated by Django 5.1.15 on 2026-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0071_alter_alertsilence_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsilence',
            name='category',
            field=models.CharField(blank=True, choices=[('disk', 'Disk usage'), ('high_disk', 'High disk usage'), ('very_high_disk', 'Very high disk usage'), ('ram', 'Ram usage'), ('high_ram', 'High RAM usage'), ('very_high_ram', 'Very high RAM usage'), ('cpu', 'Cpu usage'), ('high_cpu', 'High CPU usage'), ('very_high_cpu', 'Very high CPU usage'), ('service', 'Service down'), ('degraded', 'Degraded'), ('degrading', 'Degrading'), ('potentially_degrading', 'Potentially degrading'), ('temperature', 'Temperature'), ('backup', 'Backup missing'), ('unreachable', 'Component unreachable'), ('untracked', 'Backup untracked'), ('untracked_metrics', 'Untracked metrics'), ('folder', 'Size monitoring'), ('very_high_folder', 'Folder far over expected size'), ('backup_uncleared', 'Backup & log drainage'), ('backup_overdue', 'Backup & log drainage overdue'), ('undrained_folders', 'Drainage monitoring'), ('queue_stuck', 'Queue not draining')], help_text='What this silences (reports.alerting.Flag.category).', max_length=32),
        ),
    ]
