# Generated by Django 5.1.15 on 2026-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0072_alter_alertsilence_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=120)),
                ('suffix', models.CharField(max_length=255)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'comment index entry',
                'verbose_name_plural': 'comment index entries',
                'unique_together': {('system', 'suffix')},
            },
        ),
    ]
