# Generated by Django 5.1.15 on 2026-10-02 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0073_commentindexentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='default_alert_window_end',
            field=models.TimeField(default=datetime.time(21, 0), help_text='Default notification window end -- see default_alert_window_start.'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='default_alert_window_start',
            field=models.TimeField(default=datetime.time(7, 45), help_text="Default notification window start for any Monitoring Alert Group that hasn't set its own schedule. Overridden per-group by that group's own schedule, once set."),
        ),
    ]
