# Generated by Django 5.1.15 on 2026-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0074_systemconfig_default_alert_window_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedreportinstance',
            name='report_type',
            field=models.CharField(choices=[('weekly_trend', 'Weekly Operational Trend Report'), ('monthly_recurring', 'Monthly Recurring Issues Report'), ('quarterly_summary', 'Quarterly Management Summary'), ('system_attention', 'System Attention Report'), ('admin_observations', 'Administrator Observations Digest'), ('anomaly_log', 'Anomaly / Fluke Log'), ('paused_alerts', 'Paused Alerts Digest')], db_index=True, max_length=32),
        ),
    ]
