# Generated by Django 5.1.15 on 2026-10-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0075_alter_automatedreportinstance_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsilence',
            name='from_group_pause',
            field=models.BooleanField(default=False),
        ),
    ]
