#!/usr/bin/env bash
# =============================================================================
#  @@FILENAME@@ - backup freshness check for the node_exporter textfile collector.
#
#  GENERATED by the RBZ Monitoring Console (Configuration > Scripts) for @@SYSTEM@@ on
#  @@GENERATED_AT@@. Edit the definition in the console and regenerate rather than editing
#  this file: a regenerate overwrites it, and a local edit here is invisible to the console.
#
#  The Linux counterpart of the Windows check, emitting the SAME schema — the report engine
#  scans for exactly these names, so a Linux system's backups land in the same report
#  section as a Windows one with nothing downstream needing to know the difference:
#      backup_file{file="<name>",day="today|yesterday|<weekday>"} <mtime unix seconds>
#      backup_file_count                 files inside the freshness window
#      backup_check_success              1 = backup root reachable / 0 = missing
#      backup_check_timestamp_seconds    when this ran
#
#  Freshness is judged on the file's MTIME against calendar-day boundaries, matching the
#  Windows check exactly — not on the timestamp in the filename, which is only the intended
#  run time and lies if a job is re-run or a name reused.
# =============================================================================
set -uo pipefail

BACKUP_ROOT="${BACKUP_ROOT:-@@BACKUP_ROOT@@}"
FILE_GLOB="${FILE_GLOB:-@@FILE_GLOB@@}"
TEXTFILE_DIR="${TEXTFILE_DIR:-@@TEXTFILE_DIR@@}"
OUT_FILE="${OUT_FILE:-@@OUT_FILE@@}"
MIN_BYTES="${MIN_BYTES:-@@MIN_BYTES@@}"
MAX_AGE_DAYS="${MAX_AGE_DAYS:-@@MAX_AGE_DAYS@@}"

out_path="${TEXTFILE_DIR%/}/${OUT_FILE}"
tmp_path="${out_path}.$$.tmp"
now=$(date +%s)
# local midnight today, as epoch seconds — the same calendar-day boundary the Windows
# check uses, so "yesterday" means the same thing on both platforms
today_mid=$(date -d "today 00:00:00" +%s)

check_ok=1
file_lines=""
count=0

if [ -d "$BACKUP_ROOT" ]; then
  while IFS= read -r -d '' f; do
    size=$(stat -c %s "$f")
    [ "$size" -ge "$MIN_BYTES" ] || continue
    mtime=$(stat -c %Y "$f")
    f_mid=$(date -d "@$mtime" -d "$(date -d "@$mtime" +%Y-%m-%d) 00:00:00" +%s 2>/dev/null \
            || date -d "$(date -d "@$mtime" +%Y-%m-%d)" +%s)
    age_days=$(( (today_mid - f_mid) / 86400 ))
    # a future mtime (clock skew) counts as today, exactly as the Windows check does
    [ "$age_days" -lt 0 ] && age_days=0
    [ "$age_days" -le "$MAX_AGE_DAYS" ] || continue      # beyond the window -> stale, skipped
    case "$age_days" in
      0) day="today" ;;
      1) day="yesterday" ;;
      # older but still inside the window is named by its weekday rather than being squeezed
      # into "yesterday", which would simply be untrue
      *) day=$(date -d "@$mtime" +%A | tr '[:upper:]' '[:lower:]') ;;
    esac
    name=$(basename "$f")
    name=${name//\\/\\\\}
    name=${name//\"/\\\"}
    file_lines="${file_lines}backup_file{file=\"${name}\",day=\"${day}\"} ${mtime}"$'\n'
    count=$((count + 1))
  done < <(find "$BACKUP_ROOT" -maxdepth 1 -type f -name "$FILE_GLOB" -print0 2>/dev/null)
else
  check_ok=0
fi

mkdir -p "$TEXTFILE_DIR"
{
  echo '# HELP backup_file A backup file modified yesterday or today (day label = which). Value = file mtime (unix seconds) = when it was generated.'
  echo '# TYPE backup_file gauge'
  printf '%s' "$file_lines"
  echo '# HELP backup_file_count Number of backup files modified yesterday or today.'
  echo '# TYPE backup_file_count gauge'
  echo "backup_file_count ${count}"
  echo '# HELP backup_check_success Whether the folder scan succeeded (1) or failed (0 = folder missing).'
  echo '# TYPE backup_check_success gauge'
  echo "backup_check_success ${check_ok}"
  echo '# HELP backup_check_timestamp_seconds Unix time when the scan last ran.'
  echo '# TYPE backup_check_timestamp_seconds gauge'
  echo "backup_check_timestamp_seconds ${now}"
} > "$tmp_path"

# atomic swap, so the collector never reads a half-written file
mv -f "$tmp_path" "$out_path"
[ "$check_ok" -eq 0 ] && exit 1
exit 0
