<#
  @@FILENAME@@ - backup freshness check for the @@EXPORTER@@ textfile collector.

  GENERATED by the RBZ Monitoring Console (Configuration > Scripts) for @@SYSTEM@@ on
  @@GENERATED_AT@@. Edit the definition in the console and regenerate rather than editing
  this file: a regenerate overwrites it, and a local edit here is invisible to the console.

  Emits the shared backup schema every sibling check uses. The metric names, labels and
  label values are FIXED - the report engine scans for exactly these, and the textfile
  collector errors if two .prom files in one directory describe the same metric differently:
      backup_file{file="<name>",day="today|yesterday|<weekday>"} <mtime unix seconds>
      backup_file_count                 files inside the freshness window
      backup_check_success              1 = backup root reachable / 0 = missing
      backup_check_timestamp_seconds    when this ran

  MaxAgeDays is the freshness window in calendar days. 1 = the usual today-or-yesterday
  check; raise it for a system that does not back up daily (BSA runs every third day, so
  a daily window would report NO BACKUP on the two days in between while the policy is
  actually being met).
#>
param(
    [string]$BackupRoot  = '@@BACKUP_ROOT@@',
    [string]$FileName    = '@@FILE_GLOB@@',
    [string]$TextfileDir = '@@TEXTFILE_DIR@@',
    [string]$OutFile     = '@@OUT_FILE@@',
    [ValidateSet('LastWriteTime', 'CreationTime')]
    [string]$TimeField   = '@@TIME_FIELD@@',
    [long]$MinBytes      = @@MIN_BYTES@@,
    [ValidateRange(1, 366)]
    [int]$MaxAgeDays     = @@MAX_AGE_DAYS@@
)

$ErrorActionPreference = 'Stop'
$outPath = Join-Path $TextfileDir $OutFile
$tmpPath = "$outPath.$PID.tmp"
$now     = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
$todayMid = (Get-Date).Date                # local midnight today

$checkOk = 1
$fileLines = @()

if (Test-Path -LiteralPath $BackupRoot) {
    # ONE row per CURRENT .bak. The folder is flat and keeps old backups, so a file existing does
    # NOT prove a current one is present -> judge each on its own mtime against the policy window.
    Get-ChildItem -LiteralPath $BackupRoot -Filter $FileName -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Length -ge $MinBytes } | ForEach-Object {
            $ts = $_.$TimeField
            # whole calendar days between the file's date and today; <=0 (incl. a future mtime
            # from clock skew) counts as today, exactly as the previous $ts -ge $todayMid test did
            $ageDays = [int][math]::Floor(($todayMid - $ts.Date).TotalDays)
            if ($ageDays -le $MaxAgeDays) {                    # beyond the window -> stale, skipped
                # today/yesterday keep their usual meaning; anything older inside the window is
                # named by its weekday ("wednesday") rather than being squeezed into one of those
                # two. Calling a 3-day-old .bak "yesterday" would simply be untrue, and the window
                # here is far shorter than a week so a weekday name is never ambiguous.
                $day = switch ($ageDays) {
                    { $_ -le 0 } { 'today';     break }
                    1            { 'yesterday'; break }
                    default      { $ts.ToString('dddd', [Globalization.CultureInfo]::InvariantCulture).ToLowerInvariant() }
                }
                # label: the filename (it already carries the YYYYMMDD_HHMMSS stamp, so no folder needed)
                $label = ($_.Name) -replace '\\', '\\' -replace '"', '\"'
                $epoch = ([DateTimeOffset]$ts).ToUnixTimeSeconds()   # value = file mtime (unix secs) = when generated
                $fileLines += ('backup_file{{file="{0}",day="{1}"}} {2}' -f $label, $day, $epoch)
            }
        }
}
else {
    $checkOk = 0
}

$count = $fileLines.Count

$lines = @(
    '# HELP backup_file A backup file modified yesterday or today (day label = which). Value = file mtime (unix seconds) = when it was generated.'
    '# TYPE backup_file gauge'
)
if ($fileLines.Count) { $lines += $fileLines }
$lines += @(
    '# HELP backup_file_count Number of backup files modified yesterday or today.'
    '# TYPE backup_file_count gauge'
    "backup_file_count $count"
    '# HELP backup_check_success Whether the folder scan succeeded (1) or failed (0 = folder missing).'
    '# TYPE backup_check_success gauge'
    "backup_check_success $checkOk"
    '# HELP backup_check_timestamp_seconds Unix time when the scan last ran.'
    '# TYPE backup_check_timestamp_seconds gauge'
    "backup_check_timestamp_seconds $now"
)

if (-not (Test-Path $TextfileDir)) { New-Item -ItemType Directory -Path $TextfileDir -Force | Out-Null }
Set-Content -Path $tmpPath -Value $lines -Encoding ascii
Move-Item -Path $tmpPath -Destination $outPath -Force   # atomic swap
if ($checkOk -eq 0) { exit 1 }
exit 0
