@echo off
REM ===========================================================================
REM  @@FILENAME@@ - launch @@PS1_NAME@@ for Task Scheduler.
REM
REM  GENERATED by the RBZ Monitoring Console (Configuration > Scripts) for @@SYSTEM@@
REM  on @@GENERATED_AT@@. Regenerate from the console rather than editing here.
REM
REM  Wraps the PowerShell check so the scheduled task is a single .bat entry and all
REM  output lands in the log below for no-console (scheduled) diagnosis. Any extra args
REM  are passed through to the .ps1 (e.g. -BackupRoot, -TextfileDir).
REM
REM  Deploy: Task Scheduler, daily AFTER the backup window, as an account that can read
REM  the backup root and write the exporter's textfile directory.
REM ===========================================================================
setlocal EnableExtensions
cd /d "%~dp0"
set "LOG=%~dp0@@LOG_NAME@@"
set "PS1=%~dp0@@PS1_NAME@@"

> "%LOG%" echo ===== @@SYSTEM@@ backup check run: %DATE% %TIME% (user: %USERNAME%) =====

REM --- locate PowerShell ---
set "PWSH="
where powershell >nul 2>&1 && set "PWSH=powershell"
if not defined PWSH (
    >> "%LOG%" echo [x] powershell.exe NOT found on PATH for this account.
    type "%LOG%"
    exit /b 9
)

if not exist "%PS1%" (
    >> "%LOG%" echo [x] Missing script: "%PS1%"
    type "%LOG%"
    exit /b 9
)

>> "%LOG%" echo [*] Running @@PS1_NAME@@ %*
%PWSH% -NoProfile -ExecutionPolicy Bypass -File "%PS1%" %* >> "%LOG%" 2>&1
set "RC=%ERRORLEVEL%"

if "%RC%"=="0" (
    >> "%LOG%" echo [OK] Backup root reachable, metrics written. Done: %DATE% %TIME%
) else if "%RC%"=="1" (
    >> "%LOG%" echo [!] Backup root MISSING/unreadable - wrote backup_check_success 0. Done: %DATE% %TIME%
) else (
    >> "%LOG%" echo [x] @@PS1_NAME@@ failed with exit %RC%. Done: %DATE% %TIME%
)

type "%LOG%"
endlocal & exit /b %RC%
