"""Phase 4/5/6 of the Automated Reports spec ("New Promt.txt"), generalised: ONE engine
producing all six report types from section 17, all sharing the exact section-12 structure
(spec: "Every report generated by the system... must follow this exact section structure. Do
not let individual report types drift into inconsistent formats over time.") -- only the
window, emphasis, and narrative framing differ per type; the underlying classification
(reports.trend_classification), correlation (reports.comment_correlation), theming
(reports.comment_themes) and totals-integrity (reports.totals_integrity) modules are shared
verbatim.

Grew out of the original single-purpose Weekly Operational Trend Report (Phase 4 item 11:
"Start with one report type end-to-end... before building the rest") once that one report was
validated and the remaining five in section 17 were built on the same proven shape.
"""
from __future__ import annotations

import datetime
from dataclasses import dataclass, field

from django.utils import timezone

from .ai_narrative import NarrativeResult, run_narrative
from .comment_themes import theme_digest
from .totals_integrity import detect_totals_anomalies, totals_anomaly_to_dict
from .trend_classification import (BORDERLINE, ONE_OFF, PERSISTENT, RECURRING,
                                   IssueClassification, classify_all)

# ---------------------------------------------------------------------------------------
# Section 17's own table, verbatim: key -> label/purpose/cadence/window/cron. `cron` is None
# for the one report explicitly exempted from a schedule ("System Attention... so this
# doesn't wait for a scheduled cycle") -- that type is regenerated on demand, at view time,
# instead (see reports/views.py's automated_report_type view).
# ---------------------------------------------------------------------------------------
REPORT_TYPES = {
    "weekly_trend": {
        "label": "Weekly Operational Trend Report",
        "purpose": "Short-window view of what changed, what's recurring, what's noise — "
                  "the fastest feedback loop for admins.",
        "cadence": "Weekly",
        "window_days": 7,
        # Friday 10:00, not Monday 06:15 (2026-09-07, on request) -- matches
        # deploy/gms/folder_exporter.yml's own automated_report_weekly_trend job, which is
        # what actually drives this; this string is documentation of that schedule, not itself
        # the trigger (see that job's own comment for why it moved).
        "cron": "0 10 * * 5",
    },
    "monthly_recurring": {
        "label": "Monthly Recurring Issues Report",
        "purpose": "Ranks recurring issues by frequency + duration + severity + persistence; "
                  "the primary input for prioritisation decisions.",
        "cadence": "Monthly",
        "window_days": 30,
        "cron": "0 6 1 * *",
    },
    "quarterly_summary": {
        "label": "Quarterly Management Summary",
        "purpose": "Executive-level rollup for management, following the full section-12 "
                  "structure, written for a non-technical audience.",
        "cadence": "Quarterly",
        "window_days": 90,
        "cron": "30 6 1 1,4,7,10 *",
    },
    "system_attention": {
        "label": "System Attention Report",
        "purpose": "Always-current list of systems meeting the 'requires attention' "
                  "criteria — regenerated whenever it's opened, not on a fixed schedule.",
        "cadence": "Continuously updated",
        "window_days": 7,
        "cron": None,
    },
    "admin_observations": {
        "label": "Administrator Observations Digest",
        "purpose": "Themed summary of what admins are repeatedly commenting on, correlated "
                  "against monitoring data — operational-process patterns kept separate "
                  "from infrastructure ones.",
        "cadence": "Monthly",
        "window_days": 30,
        "cron": "15 6 1 * *",
    },
    "anomaly_log": {
        "label": "Anomaly / Fluke Log",
        "purpose": "Informational only, not alarmed — records what was investigated and "
                  "ruled out as noise, so that history isn't lost.",
        "cadence": "Weekly",
        "window_days": 7,
        "cron": "45 6 * * 1",
    },
}


@dataclass
class SystemAttention:
    """One row of "System Areas Requiring Attention" -- a system ranked by how much of its
    own recent history is Persistent/Recurring trouble, not by raw alert count (section 7:
    explain why each system deserves attention)."""
    system: str
    persistent_count: int
    recurring_count: int
    worst_band: str
    issues: list = field(default_factory=list)


@dataclass
class AutomatedReport:
    """Every section 12 of the spec asks for, plus the metadata the Automated Reports tile
    (Phase 6) and history screen need. Identical shape for all six report_types -- only the
    window and which sections carry the most weight differ (section 12: no per-type drift)."""
    report_type: str
    label: str
    purpose: str
    cadence: str
    generated_at: datetime.datetime
    window_days: int
    window_start: datetime.datetime
    window_end: datetime.datetime
    ai_provider: str
    ai_requested_provider: str
    ai_error: str
    narrative: dict                      # NARRATIVE_SECTION_KEYS -> prose
    recurring_issues: list               # IssueClassification, PERSISTENT + RECURRING, ranked
    cleared_issues: list                 # dicts, see _cleared_issues -- "cleared over the past window"
    system_attention: list               # SystemAttention, ranked
    anomalies: list                      # IssueClassification, BORDERLINE only
    one_off_issues: list                 # IssueClassification, ONE_OFF only
    commented_issues: list               # IssueClassification with at least one comment, ranked
    themes: list                         # comment_themes.theme_digest() output (admin_observations only)
    totals_anomalies: list               # totals_integrity.TotalsAnomaly, non-monotonic totals
    total_issues: int
    total_systems: int                   # every system in the topology, not just ones with an issue


def _cleared_issues(issues: list, window_end: datetime.datetime) -> list:
    """Persistent/Recurring findings that fired earlier in the window, then had zero activity
    for the rest of it through window_end -- spec item 3a: "Cleared over the past [window]".
    Same underlying idea as the Automated Monitoring progress-update report's own "recurring
    findings, fixed and stayed fixed" section, narrowed to fit entirely within THIS report's own
    existing window (no cross-run history, no finding-history table) -- computed from `i.
    occurrences` (classify_all's own chronological ObservedFlag list per finding), the same
    single-window dataset every other section already uses. Deliberately doesn't overclaim: a
    finding that stopped firing just 1-2 days before window_end still qualifies (spec's own
    words: "'stayed fixed' here can mean as little as 2-3 clean days... real signal, but weaker
    than a multi-week confirmation") -- `clean_days` rides along so the template can phrase it
    honestly ("quiet for the remainder of this window", never an unqualified "fixed"), not
    silently treat a 1-day gap the same as a 6-day one."""
    end_day = window_end.date()
    out = []
    for i in issues:
        if i.label not in (PERSISTENT, RECURRING) or not i.occurrences:
            continue
        last_active_day = i.occurrences[-1].created_at.date()
        clean_days = (end_day - last_active_day).days
        if clean_days >= 1:
            out.append({
                "system": i.system, "flag_key": i.flag_key, "category": i.category,
                "label": i.label, "last_active": last_active_day.isoformat(),
                "clean_days": clean_days, "distinct_days": i.distinct_days,
                "latest_text": i.latest_text,
            })
    out.sort(key=lambda r: r["clean_days"], reverse=True)
    return out


def _system_attention_rows(issues: list) -> list:
    by_system: dict = {}
    for i in issues:
        if i.label not in (PERSISTENT, RECURRING):
            continue
        row = by_system.setdefault(i.system, SystemAttention(
            system=i.system, persistent_count=0, recurring_count=0, worst_band="amber"))
        if i.label == PERSISTENT:
            row.persistent_count += 1
        else:
            row.recurring_count += 1
        if i.worst_band == "red":
            row.worst_band = "red"
        row.issues.append(i)
    rows = list(by_system.values())
    rows.sort(key=lambda r: (r.worst_band == "red", r.persistent_count * 2 + r.recurring_count),
             reverse=True)
    return rows


def generate_automated_report(report_type: str, *, window_days: int | None = None,
                              now=None) -> AutomatedReport:
    """One report, end to end: classify (Phase 3), narrate (Phase 4/ai_narrative,
    report_type-aware), assemble into the spec's own section structure. Deterministic given
    the same data and the same narrative_provider config for every section except the AI
    provider's own prose (the statistical sections never vary between two runs of the same
    window)."""
    if report_type not in REPORT_TYPES:
        raise ValueError(f"Unknown Automated Report type: {report_type!r}")
    spec = REPORT_TYPES[report_type]
    window_days = window_days or spec["window_days"]
    now = now or timezone.now()
    window_start = now - datetime.timedelta(days=window_days)

    issues = classify_all(window_days=window_days, now=now)
    themes = theme_digest(window_days=window_days, now=now) if report_type == "admin_observations" else []
    totals = [totals_anomaly_to_dict(a) for a in detect_totals_anomalies(window_days=window_days, now=now)]

    from .services import list_systems
    total_systems = len(list_systems())

    recurring_issues = [i for i in issues if i.label in (PERSISTENT, RECURRING)]
    anomalies = [i for i in issues if i.label == BORDERLINE]
    one_off_issues = [i for i in issues if i.label == ONE_OFF]
    commented = sorted((i for i in issues if i.comments), key=lambda i: i.significance, reverse=True)
    cleared_issues = _cleared_issues(issues, now)
    # Computed BEFORE run_narrative (2026-09-10, item 10a) so §09's own bullet can count the
    # SAME "Fix needed?/Resolved never recorded" population the highlighted §04 rows show,
    # rather than the older, different "zero admin comments" signal it used to describe --
    # the spec's own instruction: "let §09's text become a one-line summary count referencing
    # those highlighted rows" (the NEW rows, not a separately-computed old metric).
    current_actions = _current_actions(recurring_issues)
    action_unset_count = sum(
        1 for i in recurring_issues
        if (a := current_actions.get((i.system, i.flag_key))) is None or a.is_unset)

    result: NarrativeResult = run_narrative(
        issues, window_days=window_days, report_type=report_type, themes=themes,
        totals_anomalies=totals, action_unset_count=action_unset_count)

    return AutomatedReport(
        report_type=report_type, label=spec["label"], purpose=spec["purpose"],
        cadence=spec["cadence"], generated_at=now, window_days=window_days,
        window_start=window_start, window_end=now,
        ai_provider=result.provider, ai_requested_provider=result.requested_provider,
        ai_error=result.error or "", narrative=result.sections,
        cleared_issues=cleared_issues,
        recurring_issues=recurring_issues, system_attention=_system_attention_rows(issues),
        anomalies=anomalies, one_off_issues=one_off_issues, commented_issues=commented,
        themes=themes, totals_anomalies=totals, total_issues=len(issues),
        total_systems=total_systems,
    )


# ---------------------------------------------------------------------------------------
# Serialization -- JSON-safe dicts for AutomatedReportInstance.content (Phase 5 item 13:
# versioned storage) and for rendering. templates/reports/automated_report_download.html is
# now the ONE template for both the in-app view and the downloaded file (views.py's
# automated_report_detail renders it inline; automated_report_download renders the same
# template as an attachment) -- e-mail keeps its own Outlook-safe table-based template
# (automated_report_email.html) since Outlook's renderer can't handle this one's CSS.
# Dicts rather than dataclasses so old stored
# instances stay renderable even if the dataclass shapes above evolve later -- the same
# discipline ReportSubmission.report_content already uses.
# ---------------------------------------------------------------------------------------

def _issue_to_dict(i: IssueClassification, actions: dict | None = None) -> dict:
    action = (actions or {}).get((i.system, i.flag_key))
    return {
        "system": i.system, "flag_key": i.flag_key, "category": i.category,
        "latest_text": i.latest_text, "label": i.label, "confidence": i.confidence,
        "emerging": i.emerging, "distinct_days": i.distinct_days, "span_days": i.span_days,
        "coverage": i.coverage, "first_seen": i.first_seen.isoformat(),
        "last_seen": i.last_seen.isoformat(), "worst_band": i.worst_band,
        "comments": [{"created_at": dt.isoformat(), "text": c} for dt, c in i.comments],
        # SNAPSHOTTED at generation time (2026-09-10, item 10a: "each report run stores that
        # run's value for these four fields against the finding, even when the value is just
        # carried forward unchanged") -- whatever AutomatedFindingAction currently holds for
        # this (system, flag_key), frozen into this run permanently, same as every other field
        # here. `action_unset` drives the "highlight rows needing attention" styling directly
        # in the template without it needing its own tri-state logic.
        "action_comment": action.comment if action else "",
        "action_fix_needed": action.fix_needed if action else "",
        "action_resolved": action.resolved if action else "",
        "action_unset": action.is_unset if action else True,
    }


def _system_attention_to_dict(row: SystemAttention, actions: dict | None = None) -> dict:
    return {
        "system": row.system, "persistent_count": row.persistent_count,
        "recurring_count": row.recurring_count, "worst_band": row.worst_band,
        "issues": [_issue_to_dict(i, actions) for i in row.issues],
    }


def _current_actions(issues: list) -> dict:
    """{(system, flag_key): AutomatedFindingAction} for every finding this report is about to
    serialize -- ONE batched query, not one per finding (2026-09-10, item 10a's own
    snapshotting step)."""
    from .models import AutomatedFindingAction

    pairs = {(i.system, i.flag_key) for i in issues}
    if not pairs:
        return {}
    systems = {s for s, _f in pairs}
    rows = AutomatedFindingAction.objects.filter(system__in=systems)
    return {(a.system, a.flag_key): a for a in rows if (a.system, a.flag_key) in pairs}


def report_to_dict(r: AutomatedReport) -> dict:
    """Everything the detail template/e-mail needs to re-render this exact instance,
    permanently -- see AutomatedReportInstance.content."""
    actions = _current_actions(r.recurring_issues + r.anomalies + r.one_off_issues)
    return {
        "report_type": r.report_type, "label": r.label, "purpose": r.purpose,
        "cadence": r.cadence, "generated_at": r.generated_at.isoformat(),
        "window_days": r.window_days, "window_start": r.window_start.isoformat(),
        "window_end": r.window_end.isoformat(), "ai_provider": r.ai_provider,
        "ai_requested_provider": r.ai_requested_provider, "ai_error": r.ai_error,
        "narrative": r.narrative,
        "recurring_issues": [_issue_to_dict(i, actions) for i in r.recurring_issues],
        "cleared_issues": r.cleared_issues,
        "system_attention": [_system_attention_to_dict(s, actions) for s in r.system_attention],
        "anomalies": [_issue_to_dict(i) for i in r.anomalies],
        "one_off_issues": [_issue_to_dict(i) for i in r.one_off_issues],
        "commented_issues": [_issue_to_dict(i) for i in r.commented_issues],
        "themes": r.themes, "totals_anomalies": r.totals_anomalies,
        "total_issues": r.total_issues, "total_systems": r.total_systems,
    }
